### ISSUE TITLE
I have some doubts

### ISSUE THREAD

**Issue by wnark** [damian-pastorini/reldens-skeleton#5]
Hello, I am trying to run your demo on serverless for my elective classwork, and I have some problems.

When this demo is playing games, does the communication between the browser and the server use websocket?
Because serverless can only use websocket to keep the server communicating with the browser.

thanks

**Comment by damian-pastorini** [comment]
Hi @wnark , 

First, for questions I would recommend you to join our discord channel https://discord.gg/HuJMxUY and in your case Colyseus channel as well https://discord.gg/RY8rRS7 that way you will be able to get quick answers faster and avoid creating issues for implementation doubts.
That said, Reldes is build with Colyseus which indeed use WebSocket, here you can find the server documentation related:
https://docs.colyseus.io/
For last if you are having any specific error please always include the log and specify as much information as possible so we can reproduce and fix.

Thanks again!
